services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-recipe
    networks:
      - my_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    name: recipe_volume
#docker-compose -f "docker-compose.yml" up -d
